### ISSUE TITLE
Exception in server tick loop [Fabric 1.21.1 on 0.16.9]

### ISSUE THREAD

**Issue by suerion** [Meloweh/Better-Wolf-Companion-Mod#1]
Hey, i had added the Mod on my server, it is a Huge modpack, but it works fine for me, now i'm working on compat issues. 

After adding your mod, it crash the server on startup

Crash Log
https://mclo.gs/pcfcj9X

If you need the latest log, i would add it later

**Comment by Meloweh** [comment]
Hey, thanks for submitting the issue.

I attempted to fix the issue here:
https://github.com/Meloweh/Better-Wolf-Companion-Mod/releases/tag/Bugs

Could you please verify if the exception has been resolved?

**Comment by suerion** [comment]
hey, will it test in a few minutes ;)

**Comment by suerion** [comment]
Startup is working now, will test next to join the server

**Comment by Meloweh** [comment]
Could you join? :)

**Comment by suerion** [comment]
Hey sorry, had an other issue on my side, but yes i could join

**Comment by Meloweh** [comment]
Thank you for your time! I assume that the issue got resolved. I will close this issue for now then.
